import api from './_client'

export { authApi }          from './auth'
export { usersApi }         from './users'
export { customersApi }     from './customers'
export { addressesApi }     from './addresses'
export { categoriesApi }    from './categories'
export { productsApi }      from './products'
export { ordersApi }        from './orders'
export { bannersApi }       from './banners'
export { couponsApi }       from './coupons'
export { discountsApi }     from './discounts'
export { zonesApi }         from './zones'
export { reviewsApi }       from './reviews'
export { paymentsApi }      from './payments'
export { notificationsApi } from './notifications'
export { permissionsApi }   from './permissions'
export { settingsApi }      from './settings'
export { favoritesApi }     from './favorites'
export { statsApi }         from './stats'

export default api
